package com.ibagroup.common.dao.enums;

public enum State {

    DEFAULT,
    AUTHENTICATION_ENTER_NAME,
    AUTHENTICATION_ENTER_EMAIL,
    ADDING_PRODUCT_ENTER_NAME,
    ADDING_PRODUCT_ENTER_PROTEINS,
    ADDING_PRODUCT_ENTER_CARBS,
    ADDING_PRODUCT_ENTER_FATS,
    SELECT_PRODUCT_NAME,
    NEW_COURSE_ENTER_PRODUCT_WEIGHT,
    EXISTING_COURSE_ENTER_PRODUCT_WEIGHT


}
