services:
  mongodb:
    image: mongo:latest
    container_name: calorie-counter-mongodb
    restart: always
    env_file:
      - calorie-counter-common/src/main/resources/.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: supersecretpassword
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    container_name: calorie-counter-mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongouser
      ME_CONFIG_MONGODB_ADMINPASSWORD: supersecretpassword
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    ports:
      - 8081:8081
    depends_on:
      - mongodb
  postgresql:
    image: postgres:latest
    container_name: calorie-counter-postgresql
    restart: always
    env_file:
      - calorie-counter-common/src/main/resources/.env
    environment:
      - POSTGRES_DB=authorization_DB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432